version: "3.8"

services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:5.7
        command: --slow-query-log=TRUE --slow-launch-time=5
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=biblionet
            - MYSQL_USER=biblionet
            - MYSQL_PASSWORD=biblionet
        volumes:
            - ../sql:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root 
        ports:
            - 8080:80
        depends_on:
            - db
        
